// ─────────────────────────────────────────────────────────────────────────────
// Baseline climate data — Our World in Data / Global Carbon Project / IRENA
// Renewable % = share of electricity from renewables (excl. nuclear unless noted)
// co2PerCapita = tonnes CO2 per person per year (2022)
// ─────────────────────────────────────────────────────────────────────────────

/** Generate a flag emoji from an ISO-3166-1 alpha-2 country code. */
export function getFlagEmoji(code: string): string {
  return code
    .toUpperCase()
    .replace(/./g, (ch) => String.fromCodePoint(127397 + ch.charCodeAt(0)));
}

export interface RenewableEntry {
  name: string;
  percent: number;
  breakdown: Record<string, number>;
}

export interface CarbonEntry {
  name: string;
  co2PerCapita: number;
  year: number;
}

// ─── Renewable electricity share ─────────────────────────────────────────────
export const BASELINE_RENEWABLE: Record<string, RenewableEntry> = {
  // ── Europe – Western ──────────────────────────────────────────────────────
  NO: { name: "Norway",          percent: 98.5, breakdown: { hydro: 91, wind: 6,  solar: 0.1, fossil: 2   } },
  IS: { name: "Iceland",         percent: 99.9, breakdown: { hydro: 70, geo: 30,  fossil: 0   } },
  SE: { name: "Sweden",          percent: 98.6, breakdown: { hydro: 44, wind: 17, nuclear: 30, solar: 1, fossil: 1 } },
  CH: { name: "Switzerland",     percent: 91.0, breakdown: { hydro: 57, solar: 6, nuclear: 27, wind: 0.2, fossil: 9 } },
  FR: { name: "France",          percent: 92.0, breakdown: { nuclear: 72, hydro: 11, wind: 7, solar: 2, fossil: 8 } },
  AT: { name: "Austria",         percent: 78.0, breakdown: { hydro: 62, wind: 10, solar: 5, fossil: 22  } },
  PT: { name: "Portugal",        percent: 61.0, breakdown: { hydro: 26, wind: 26, solar: 6, fossil: 39  } },
  DK: { name: "Denmark",         percent: 77.0, breakdown: { wind: 55, solar: 6,  hydro: 0.1, fossil: 23 } },
  DE: { name: "Germany",         percent: 59.0, breakdown: { wind: 31, solar: 11, hydro: 3.5, fossil: 41 } },
  ES: { name: "Spain",           percent: 57.0, breakdown: { wind: 23, solar: 14, hydro: 7, nuclear: 20, fossil: 43 } },
  GB: { name: "United Kingdom",  percent: 50.0, breakdown: { wind: 29, nuclear: 15, solar: 5, hydro: 2, fossil: 50 } },
  FI: { name: "Finland",         percent: 85.0, breakdown: { hydro: 24, nuclear: 34, wind: 14, fossil: 15 } },
  IE: { name: "Ireland",         percent: 42.0, breakdown: { wind: 34, hydro: 3, solar: 1, fossil: 58  } },
  NL: { name: "Netherlands",     percent: 36.0, breakdown: { wind: 22, solar: 11, fossil: 64  } },
  BE: { name: "Belgium",         percent: 31.0, breakdown: { nuclear: 46, wind: 13, solar: 7, fossil: 69 } },
  IT: { name: "Italy",           percent: 40.0, breakdown: { hydro: 18, solar: 11, wind: 7, fossil: 60  } },
  LU: { name: "Luxembourg",      percent: 33.0, breakdown: { hydro: 6, wind: 14, solar: 10, fossil: 67  } },
  NZ: { name: "New Zealand",     percent: 85.0, breakdown: { hydro: 57, wind: 9, solar: 2, fossil: 15   } },

  // ── Europe – Eastern & Nordic ─────────────────────────────────────────────
  PL: { name: "Poland",          percent: 27.0, breakdown: { wind: 14, solar: 5, hydro: 1, fossil: 73  } },
  CZ: { name: "Czech Republic",  percent: 43.0, breakdown: { nuclear: 38, hydro: 2, solar: 3, wind: 1, fossil: 57 } },
  SK: { name: "Slovakia",        percent: 28.0, breakdown: { nuclear: 55, hydro: 15, wind: 0.5, solar: 2, fossil: 72 } },
  HU: { name: "Hungary",         percent: 18.0, breakdown: { nuclear: 46, solar: 9, wind: 2, hydro: 0.5, fossil: 82 } },
  RO: { name: "Romania",         percent: 45.0, breakdown: { hydro: 28, wind: 13, nuclear: 18, solar: 3, fossil: 55 } },
  BG: { name: "Bulgaria",        percent: 25.0, breakdown: { nuclear: 37, hydro: 7, wind: 3, solar: 5, fossil: 75 } },
  SI: { name: "Slovenia",        percent: 42.0, breakdown: { hydro: 26, nuclear: 37, solar: 5, fossil: 58 } },
  HR: { name: "Croatia",         percent: 55.0, breakdown: { hydro: 42, wind: 11, solar: 2, fossil: 45  } },
  EE: { name: "Estonia",         percent: 38.0, breakdown: { wind: 30, solar: 3, biomass: 5, fossil: 62 } },
  LV: { name: "Latvia",          percent: 82.0, breakdown: { hydro: 67, wind: 7, biomass: 8, fossil: 18 } },
  LT: { name: "Lithuania",       percent: 42.0, breakdown: { wind: 28, solar: 5, hydro: 4, biomass: 5, fossil: 58 } },
  GR: { name: "Greece",          percent: 38.0, breakdown: { wind: 18, solar: 14, hydro: 6, fossil: 62  } },
  CY: { name: "Cyprus",          percent: 22.0, breakdown: { solar: 18, wind: 4, fossil: 78  } },
  MT: { name: "Malta",           percent: 14.0, breakdown: { solar: 12, wind: 2, fossil: 86  } },
  UA: { name: "Ukraine",         percent: 67.0, breakdown: { nuclear: 56, hydro: 7, wind: 3, solar: 5, fossil: 33 } },
  BY: { name: "Belarus",         percent:  4.0, breakdown: { hydro: 1, wind: 1, solar: 0.5, nuclear: 40, fossil: 96 } },
  MD: { name: "Moldova",         percent: 12.0, breakdown: { hydro: 10, wind: 1, solar: 1, fossil: 88  } },

  // ── Western Balkans & Caucasus ────────────────────────────────────────────
  RS: { name: "Serbia",          percent: 38.0, breakdown: { hydro: 32, wind: 5, solar: 1, fossil: 62  } },
  ME: { name: "Montenegro",      percent: 58.0, breakdown: { hydro: 52, wind: 5, solar: 1, fossil: 42  } },
  BA: { name: "Bosnia & Herz.",  percent: 52.0, breakdown: { hydro: 45, wind: 4, solar: 1, fossil: 48  } },
  MK: { name: "N. Macedonia",    percent: 32.0, breakdown: { hydro: 26, wind: 4, solar: 2, fossil: 68  } },
  AL: { name: "Albania",         percent: 97.0, breakdown: { hydro: 97, wind: 0, solar: 0, fossil: 3   } },
  GE: { name: "Georgia",         percent: 82.0, breakdown: { hydro: 80, wind: 1, solar: 0.5, fossil: 18 } },
  AM: { name: "Armenia",         percent: 40.0, breakdown: { hydro: 28, nuclear: 33, solar: 5, fossil: 60 } },
  AZ: { name: "Azerbaijan",      percent: 18.0, breakdown: { hydro: 15, wind: 2, solar: 1, fossil: 82  } },

  // ── Russia & Central Asia ─────────────────────────────────────────────────
  RU: { name: "Russia",          percent: 20.0, breakdown: { hydro: 17, nuclear: 20, wind: 0.3, fossil: 60 } },
  KZ: { name: "Kazakhstan",      percent:  4.0, breakdown: { hydro: 1, wind: 1, solar: 1, fossil: 96  } },
  UZ: { name: "Uzbekistan",      percent: 12.0, breakdown: { hydro: 10, wind: 1, solar: 1, fossil: 88  } },
  TM: { name: "Turkmenistan",    percent:  0.5, breakdown: { solar: 0.5, fossil: 99.5 } },
  KG: { name: "Kyrgyzstan",      percent: 94.0, breakdown: { hydro: 93, solar: 1, fossil: 6   } },
  TJ: { name: "Tajikistan",      percent: 97.0, breakdown: { hydro: 96, solar: 1, fossil: 3   } },
  MN: { name: "Mongolia",        percent: 10.0, breakdown: { wind: 6, solar: 3, hydro: 1, fossil: 90  } },

  // ── Middle East ───────────────────────────────────────────────────────────
  TR: { name: "Turkey",          percent: 45.0, breakdown: { hydro: 28, wind: 11, solar: 5, fossil: 55 } },
  IL: { name: "Israel",          percent: 12.0, breakdown: { solar: 10, fossil: 88  } },
  JO: { name: "Jordan",          percent: 22.0, breakdown: { wind: 10, solar: 11, fossil: 78  } },
  LB: { name: "Lebanon",         percent: 18.0, breakdown: { hydro: 15, solar: 3, fossil: 82  } },
  SY: { name: "Syria",           percent: 12.0, breakdown: { hydro: 10, solar: 2, fossil: 88  } },
  IQ: { name: "Iraq",            percent:  5.0, breakdown: { hydro: 4, solar: 1, fossil: 95   } },
  IR: { name: "Iran",            percent:  8.0, breakdown: { hydro: 6, nuclear: 2, fossil: 92  } },
  SA: { name: "Saudi Arabia",    percent:  3.0, breakdown: { solar: 2, fossil: 97  } },
  AE: { name: "UAE",             percent:  8.0, breakdown: { solar: 5, nuclear: 5, fossil: 92  } },
  QA: { name: "Qatar",           percent:  0.1, breakdown: { fossil: 100 } },
  KW: { name: "Kuwait",          percent:  0.2, breakdown: { solar: 0.2, fossil: 100 } },
  OM: { name: "Oman",            percent:  6.0, breakdown: { solar: 5, wind: 1, fossil: 94  } },
  YE: { name: "Yemen",           percent:  5.0, breakdown: { hydro: 2, solar: 3, fossil: 95  } },

  // ── South & Central Asia ──────────────────────────────────────────────────
  PK: { name: "Pakistan",        percent: 34.0, breakdown: { hydro: 26, nuclear: 8, wind: 1, fossil: 66 } },
  IN: { name: "India",           percent: 22.0, breakdown: { hydro: 10, wind: 6, solar: 6, fossil: 78 } },
  BD: { name: "Bangladesh",      percent:  3.0, breakdown: { solar: 2, fossil: 97  } },
  LK: { name: "Sri Lanka",       percent: 48.0, breakdown: { hydro: 35, wind: 5, solar: 6, fossil: 52 } },
  NP: { name: "Nepal",           percent: 97.0, breakdown: { hydro: 95, solar: 2, fossil: 3   } },
  BT: { name: "Bhutan",          percent: 100.0, breakdown: { hydro: 100, fossil: 0  } },
  AF: { name: "Afghanistan",     percent: 32.0, breakdown: { hydro: 28, solar: 3, wind: 1, fossil: 68 } },

  // ── East & SE Asia ────────────────────────────────────────────────────────
  CN: { name: "China",           percent: 29.0, breakdown: { hydro: 16, wind: 8, solar: 5, nuclear: 5, fossil: 71 } },
  JP: { name: "Japan",           percent: 23.0, breakdown: { hydro: 8, solar: 9, wind: 1, nuclear: 7, fossil: 77 } },
  KR: { name: "South Korea",     percent:  9.0, breakdown: { nuclear: 28, hydro: 1, solar: 4, wind: 1, fossil: 65 } },
  TW: { name: "Taiwan",          percent: 10.0, breakdown: { solar: 5, wind: 2, hydro: 2, nuclear: 9, fossil: 82 } },
  KP: { name: "North Korea",     percent: 28.0, breakdown: { hydro: 27, solar: 1, fossil: 72  } },
  MM: { name: "Myanmar",         percent: 52.0, breakdown: { hydro: 48, solar: 3, wind: 1, fossil: 48 } },
  TH: { name: "Thailand",        percent: 20.0, breakdown: { hydro: 5, solar: 8, wind: 3, fossil: 80 } },
  VN: { name: "Vietnam",         percent: 42.0, breakdown: { hydro: 29, solar: 10, wind: 3, fossil: 58 } },
  MY: { name: "Malaysia",        percent: 26.0, breakdown: { hydro: 22, solar: 4, fossil: 74  } },
  ID: { name: "Indonesia",       percent: 15.0, breakdown: { hydro: 7, solar: 2, wind: 0.1, fossil: 85 } },
  PH: { name: "Philippines",     percent: 22.0, breakdown: { hydro: 11, wind: 3, solar: 2, fossil: 78 } },
  SG: { name: "Singapore",       percent:  4.0, breakdown: { solar: 3, fossil: 97  } },
  BN: { name: "Brunei",          percent:  0.2, breakdown: { fossil: 100 } },
  KH: { name: "Cambodia",        percent: 55.0, breakdown: { hydro: 50, solar: 4, fossil: 45  } },
  LA: { name: "Laos",            percent: 88.0, breakdown: { hydro: 86, solar: 2, fossil: 12  } },
  TL: { name: "Timor-Leste",     percent: 22.0, breakdown: { solar: 10, hydro: 12, fossil: 78  } },
  MV: { name: "Maldives",        percent: 11.0, breakdown: { solar: 10, wind: 1, fossil: 89  } },

  // ── Oceania ───────────────────────────────────────────────────────────────
  AU: { name: "Australia",       percent: 35.0, breakdown: { solar: 15, wind: 13, hydro: 6, fossil: 65 } },
  PG: { name: "Papua New Guinea",percent: 40.0, breakdown: { hydro: 35, solar: 3, fossil: 60  } },
  FJ: { name: "Fiji",            percent: 62.0, breakdown: { hydro: 54, wind: 5, solar: 3, fossil: 38 } },

  // ── North America ─────────────────────────────────────────────────────────
  US: { name: "United States",   percent: 21.0, breakdown: { wind: 10, solar: 5, hydro: 6, nuclear: 18, fossil: 61 } },
  CA: { name: "Canada",          percent: 83.0, breakdown: { hydro: 60, wind: 6, nuclear: 15, fossil: 17 } },
  MX: { name: "Mexico",          percent: 25.0, breakdown: { hydro: 10, wind: 8, solar: 5, fossil: 75 } },

  // ── Central America & Caribbean ───────────────────────────────────────────
  CR: { name: "Costa Rica",      percent: 99.0, breakdown: { hydro: 75, wind: 13, solar: 1, geo: 10, fossil: 1 } },
  GT: { name: "Guatemala",       percent: 72.0, breakdown: { hydro: 46, geo: 14, wind: 6, biomass: 5, fossil: 28 } },
  HN: { name: "Honduras",        percent: 78.0, breakdown: { hydro: 40, wind: 15, solar: 14, biomass: 7, fossil: 22 } },
  SV: { name: "El Salvador",     percent: 68.0, breakdown: { hydro: 30, geo: 25, biomass: 10, solar: 3, fossil: 32 } },
  NI: { name: "Nicaragua",       percent: 58.0, breakdown: { hydro: 15, wind: 18, geo: 15, biomass: 8, solar: 2, fossil: 42 } },
  PA: { name: "Panama",          percent: 68.0, breakdown: { hydro: 58, wind: 5, solar: 4, fossil: 32  } },
  BZ: { name: "Belize",          percent: 55.0, breakdown: { hydro: 45, biomass: 8, solar: 2, fossil: 45 } },
  CU: { name: "Cuba",            percent: 12.0, breakdown: { hydro: 3, wind: 4, solar: 4, biomass: 1, fossil: 88 } },
  JM: { name: "Jamaica",         percent: 14.0, breakdown: { wind: 6, solar: 5, hydro: 3, fossil: 86  } },
  HT: { name: "Haiti",           percent: 22.0, breakdown: { hydro: 18, solar: 4, fossil: 78  } },
  DO: { name: "Dom. Republic",   percent: 25.0, breakdown: { wind: 10, solar: 8, hydro: 6, fossil: 75 } },
  TT: { name: "Trinidad & Tob.", percent:  1.0, breakdown: { solar: 1, fossil: 99  } },
  BB: { name: "Barbados",        percent: 16.0, breakdown: { solar: 12, wind: 4, fossil: 84  } },

  // ── South America ─────────────────────────────────────────────────────────
  BR: { name: "Brazil",          percent: 88.0, breakdown: { hydro: 61, wind: 12, solar: 5, fossil: 12 } },
  AR: { name: "Argentina",       percent: 38.0, breakdown: { hydro: 25, wind: 9, solar: 2, nuclear: 6, fossil: 62 } },
  CL: { name: "Chile",           percent: 56.0, breakdown: { hydro: 26, wind: 12, solar: 16, fossil: 44 } },
  CO: { name: "Colombia",        percent: 69.0, breakdown: { hydro: 66, wind: 1, solar: 1, fossil: 31 } },
  VE: { name: "Venezuela",       percent: 68.0, breakdown: { hydro: 65, solar: 2, wind: 1, fossil: 32 } },
  PE: { name: "Peru",            percent: 65.0, breakdown: { hydro: 58, wind: 4, solar: 3, fossil: 35 } },
  EC: { name: "Ecuador",         percent: 78.0, breakdown: { hydro: 73, solar: 3, wind: 1, fossil: 22 } },
  BO: { name: "Bolivia",         percent: 35.0, breakdown: { hydro: 28, wind: 4, solar: 3, fossil: 65 } },
  PY: { name: "Paraguay",        percent: 100.0, breakdown: { hydro: 100 } },
  UY: { name: "Uruguay",         percent: 98.0, breakdown: { wind: 41, hydro: 30, solar: 5, biomass: 22, fossil: 2 } },
  SR: { name: "Suriname",        percent: 62.0, breakdown: { hydro: 58, biomass: 4, fossil: 38  } },
  GY: { name: "Guyana",          percent: 28.0, breakdown: { hydro: 20, solar: 5, biomass: 3, fossil: 72 } },

  // ── North Africa ──────────────────────────────────────────────────────────
  MA: { name: "Morocco",         percent: 31.0, breakdown: { hydro: 5, wind: 16, solar: 7, fossil: 69 } },
  DZ: { name: "Algeria",         percent:  2.0, breakdown: { solar: 1.5, wind: 0.5, fossil: 98 } },
  TN: { name: "Tunisia",         percent:  7.0, breakdown: { solar: 4, wind: 3, fossil: 93  } },
  LY: { name: "Libya",           percent:  1.0, breakdown: { solar: 1, fossil: 99  } },
  EG: { name: "Egypt",           percent: 12.0, breakdown: { hydro: 7, wind: 3, solar: 2, fossil: 88 } },
  SD: { name: "Sudan",           percent: 48.0, breakdown: { hydro: 45, solar: 3, fossil: 52  } },
  SS: { name: "South Sudan",     percent:  5.0, breakdown: { hydro: 3, solar: 2, fossil: 95  } },

  // ── West Africa ───────────────────────────────────────────────────────────
  SN: { name: "Senegal",         percent: 22.0, breakdown: { hydro: 10, wind: 5, solar: 7, fossil: 78 } },
  ML: { name: "Mali",            percent: 55.0, breakdown: { hydro: 48, solar: 7, fossil: 45  } },
  BF: { name: "Burkina Faso",    percent: 28.0, breakdown: { solar: 16, hydro: 10, biomass: 2, fossil: 72 } },
  NE: { name: "Niger",           percent: 18.0, breakdown: { hydro: 8, solar: 9, fossil: 82  } },
  TD: { name: "Chad",            percent: 12.0, breakdown: { solar: 10, hydro: 2, fossil: 88  } },
  MR: { name: "Mauritania",      percent: 28.0, breakdown: { wind: 14, solar: 12, hydro: 2, fossil: 72 } },
  GM: { name: "Gambia",          percent: 10.0, breakdown: { solar: 8, wind: 2, fossil: 90  } },
  GN: { name: "Guinea",          percent: 78.0, breakdown: { hydro: 75, solar: 3, fossil: 22  } },
  SL: { name: "Sierra Leone",    percent: 58.0, breakdown: { hydro: 50, solar: 7, biomass: 1, fossil: 42 } },
  LR: { name: "Liberia",         percent: 42.0, breakdown: { hydro: 35, solar: 6, biomass: 1, fossil: 58 } },
  GH: { name: "Ghana",           percent: 42.0, breakdown: { hydro: 38, solar: 3, fossil: 58  } },
  CI: { name: "Côte d'Ivoire",   percent: 52.0, breakdown: { hydro: 38, solar: 8, biomass: 5, fossil: 48 } },
  TG: { name: "Togo",            percent: 38.0, breakdown: { hydro: 25, solar: 12, biomass: 1, fossil: 62 } },
  BJ: { name: "Benin",           percent: 14.0, breakdown: { solar: 10, hydro: 3, fossil: 86  } },
  NG: { name: "Nigeria",         percent: 22.0, breakdown: { hydro: 20, solar: 1, fossil: 78  } },

  // ── Central Africa ────────────────────────────────────────────────────────
  CM: { name: "Cameroon",        percent: 72.0, breakdown: { hydro: 68, solar: 4, fossil: 28  } },
  CF: { name: "Central Afr. Rep.",percent: 72.0, breakdown: { hydro: 60, solar: 10, biomass: 2, fossil: 28 } },
  CG: { name: "Rep. of Congo",   percent: 65.0, breakdown: { hydro: 62, solar: 3, fossil: 35  } },
  CD: { name: "DR Congo",        percent: 95.0, breakdown: { hydro: 94, solar: 1, fossil: 5   } },
  GA: { name: "Gabon",           percent: 78.0, breakdown: { hydro: 74, solar: 4, fossil: 22  } },
  GQ: { name: "Eq. Guinea",      percent: 28.0, breakdown: { hydro: 25, solar: 3, fossil: 72  } },

  // ── East Africa ───────────────────────────────────────────────────────────
  ET: { name: "Ethiopia",        percent: 97.0, breakdown: { hydro: 95, wind: 2, fossil: 3   } },
  KE: { name: "Kenya",           percent: 75.0, breakdown: { hydro: 30, wind: 15, solar: 3, geo: 27, fossil: 25 } },
  TZ: { name: "Tanzania",        percent: 55.0, breakdown: { hydro: 42, solar: 10, biomass: 3, fossil: 45 } },
  UG: { name: "Uganda",          percent: 80.0, breakdown: { hydro: 76, solar: 4, fossil: 20  } },
  RW: { name: "Rwanda",          percent: 52.0, breakdown: { hydro: 40, solar: 10, biomass: 2, fossil: 48 } },
  BI: { name: "Burundi",         percent: 84.0, breakdown: { hydro: 80, solar: 4, fossil: 16  } },
  DJ: { name: "Djibouti",        percent: 55.0, breakdown: { wind: 30, geo: 20, solar: 5, fossil: 45 } },
  ER: { name: "Eritrea",         percent: 35.0, breakdown: { hydro: 20, solar: 12, wind: 3, fossil: 65 } },
  SO: { name: "Somalia",         percent: 15.0, breakdown: { solar: 12, wind: 3, fossil: 85  } },

  // ── Southern Africa ───────────────────────────────────────────────────────
  ZA: { name: "South Africa",    percent: 10.0, breakdown: { hydro: 1, wind: 4, solar: 3, nuclear: 5, fossil: 90 } },
  AO: { name: "Angola",          percent: 55.0, breakdown: { hydro: 52, solar: 3, fossil: 45  } },
  ZM: { name: "Zambia",          percent: 84.0, breakdown: { hydro: 82, solar: 2, fossil: 16  } },
  ZW: { name: "Zimbabwe",        percent: 65.0, breakdown: { hydro: 55, solar: 8, fossil: 35  } },
  MZ: { name: "Mozambique",      percent: 88.0, breakdown: { hydro: 85, solar: 3, fossil: 12  } },
  MW: { name: "Malawi",          percent: 92.0, breakdown: { hydro: 89, solar: 3, fossil: 8   } },
  NA: { name: "Namibia",         percent: 60.0, breakdown: { hydro: 45, solar: 10, wind: 5, fossil: 40 } },
  BW: { name: "Botswana",        percent:  5.0, breakdown: { solar: 4, wind: 1, fossil: 95   } },
  SZ: { name: "Eswatini",        percent: 48.0, breakdown: { hydro: 40, solar: 6, biomass: 2, fossil: 52 } },
  LS: { name: "Lesotho",         percent: 95.0, breakdown: { hydro: 92, solar: 3, fossil: 5  } },

  // ── Indian Ocean islands ─────────────────────────────────────────────────
  MG: { name: "Madagascar",      percent: 62.0, breakdown: { hydro: 55, solar: 6, biomass: 1, fossil: 38 } },
  MU: { name: "Mauritius",       percent: 28.0, breakdown: { wind: 8, solar: 14, biomass: 4, hydro: 2, fossil: 72 } },
  KM: { name: "Comoros",         percent: 32.0, breakdown: { solar: 20, hydro: 10, biomass: 2, fossil: 68 } },
  CV: { name: "Cape Verde",      percent: 58.0, breakdown: { wind: 38, solar: 18, fossil: 42  } },
  ST: { name: "São Tomé & Pr.",  percent: 52.0, breakdown: { hydro: 40, solar: 12, fossil: 48  } },
};

// ─── Per-capita CO₂ footprint ─────────────────────────────────────────────────
export const BASELINE_CARBON: Record<string, CarbonEntry> = {
  // ── Very high emitters ────────────────────────────────────────────────────
  QA:  { name: "Qatar",           co2PerCapita: 31.7, year: 2022 },
  KW:  { name: "Kuwait",          co2PerCapita: 23.0, year: 2022 },
  TT:  { name: "Trinidad & Tob.", co2PerCapita: 23.5, year: 2022 },
  BH:  { name: "Bahrain",         co2PerCapita: 21.7, year: 2022 },
  BN:  { name: "Brunei",          co2PerCapita: 25.3, year: 2022 },
  AE:  { name: "UAE",             co2PerCapita: 20.1, year: 2022 },
  OM:  { name: "Oman",            co2PerCapita: 15.4, year: 2022 },
  AU:  { name: "Australia",       co2PerCapita: 14.8, year: 2022 },
  SA:  { name: "Saudi Arabia",    co2PerCapita: 14.0, year: 2022 },
  US:  { name: "United States",   co2PerCapita: 13.7, year: 2022 },
  KZ:  { name: "Kazakhstan",      co2PerCapita: 13.2, year: 2022 },
  TM:  { name: "Turkmenistan",    co2PerCapita: 12.7, year: 2022 },
  LU:  { name: "Luxembourg",      co2PerCapita: 12.0, year: 2022 },
  IS:  { name: "Iceland",         co2PerCapita:  9.1, year: 2022 },

  // ── High emitters ─────────────────────────────────────────────────────────
  CA:  { name: "Canada",          co2PerCapita: 11.6, year: 2022 },
  RU:  { name: "Russia",          co2PerCapita: 11.0, year: 2022 },
  KR:  { name: "South Korea",     co2PerCapita: 11.0, year: 2022 },
  JP:  { name: "Japan",           co2PerCapita:  8.5, year: 2022 },
  DE:  { name: "Germany",         co2PerCapita:  7.9, year: 2022 },
  IR:  { name: "Iran",            co2PerCapita:  7.8, year: 2022 },
  NL:  { name: "Netherlands",     co2PerCapita:  7.4, year: 2022 },
  PL:  { name: "Poland",          co2PerCapita:  7.3, year: 2022 },
  NO:  { name: "Norway",          co2PerCapita:  7.2, year: 2022 },
  LY:  { name: "Libya",           co2PerCapita:  8.8, year: 2022 },
  EE:  { name: "Estonia",         co2PerCapita:  8.6, year: 2022 },
  IL:  { name: "Israel",          co2PerCapita:  6.4, year: 2022 },
  TR:  { name: "Turkey",          co2PerCapita:  6.4, year: 2022 },
  MY:  { name: "Malaysia",        co2PerCapita:  6.4, year: 2022 },
  ZA:  { name: "South Africa",    co2PerCapita:  6.2, year: 2022 },
  CZ:  { name: "Czech Republic",  co2PerCapita:  6.2, year: 2022 },
  CN:  { name: "China",           co2PerCapita:  6.1, year: 2022 },
  BE:  { name: "Belgium",         co2PerCapita:  6.1, year: 2022 },
  NZ:  { name: "New Zealand",     co2PerCapita:  6.1, year: 2022 },
  SK:  { name: "Slovakia",        co2PerCapita:  6.3, year: 2022 },
  SI:  { name: "Slovenia",        co2PerCapita:  6.0, year: 2022 },
  FI:  { name: "Finland",         co2PerCapita:  5.9, year: 2022 },
  AT:  { name: "Austria",         co2PerCapita:  5.8, year: 2022 },
  GR:  { name: "Greece",          co2PerCapita:  5.5, year: 2022 },
  CY:  { name: "Cyprus",          co2PerCapita:  6.3, year: 2022 },
  MN:  { name: "Mongolia",        co2PerCapita:  6.5, year: 2022 },
  BY:  { name: "Belarus",         co2PerCapita:  6.5, year: 2022 },
  RS:  { name: "Serbia",          co2PerCapita:  5.1, year: 2022 },
  BA:  { name: "Bosnia & Herz.",  co2PerCapita:  5.4, year: 2022 },
  MK:  { name: "N. Macedonia",    co2PerCapita:  4.3, year: 2022 },
  ME:  { name: "Montenegro",      co2PerCapita:  4.1, year: 2022 },
  BG:  { name: "Bulgaria",        co2PerCapita:  6.0, year: 2022 },
  HU:  { name: "Hungary",         co2PerCapita:  4.0, year: 2022 },

  // ── Medium emitters ───────────────────────────────────────────────────────
  IE:  { name: "Ireland",         co2PerCapita:  5.6, year: 2022 },
  GB:  { name: "United Kingdom",  co2PerCapita:  4.8, year: 2022 },
  SG:  { name: "Singapore",       co2PerCapita:  4.6, year: 2022 },
  IQ:  { name: "Iraq",            co2PerCapita:  4.5, year: 2022 },
  ES:  { name: "Spain",           co2PerCapita:  4.4, year: 2022 },
  IT:  { name: "Italy",           co2PerCapita:  4.4, year: 2022 },
  DK:  { name: "Denmark",         co2PerCapita:  4.5, year: 2022 },
  BB:  { name: "Barbados",        co2PerCapita:  4.7, year: 2022 },
  AZ:  { name: "Azerbaijan",      co2PerCapita:  3.9, year: 2022 },
  MV:  { name: "Maldives",        co2PerCapita:  3.9, year: 2022 },
  UZ:  { name: "Uzbekistan",      co2PerCapita:  3.8, year: 2022 },
  DZ:  { name: "Algeria",         co2PerCapita:  3.9, year: 2022 },
  CH:  { name: "Switzerland",     co2PerCapita:  3.8, year: 2022 },
  FR:  { name: "France",          co2PerCapita:  3.9, year: 2022 },
  TW:  { name: "Taiwan",          co2PerCapita:  9.8, year: 2022 },
  LT:  { name: "Lithuania",       co2PerCapita:  4.0, year: 2022 },
  RO:  { name: "Romania",         co2PerCapita:  3.5, year: 2022 },
  TH:  { name: "Thailand",        co2PerCapita:  3.5, year: 2022 },
  UA:  { name: "Ukraine",         co2PerCapita:  3.5, year: 2022 },
  VN:  { name: "Vietnam",         co2PerCapita:  3.5, year: 2022 },
  LB:  { name: "Lebanon",         co2PerCapita:  3.2, year: 2022 },
  LV:  { name: "Latvia",          co2PerCapita:  2.4, year: 2022 },
  JO:  { name: "Jordan",          co2PerCapita:  1.9, year: 2022 },
  MX:  { name: "Mexico",          co2PerCapita:  3.7, year: 2022 },
  PT:  { name: "Portugal",        co2PerCapita:  3.9, year: 2022 },
  AR:  { name: "Argentina",       co2PerCapita:  4.0, year: 2022 },
  CL:  { name: "Chile",           co2PerCapita:  4.1, year: 2022 },
  SR:  { name: "Suriname",        co2PerCapita:  5.8, year: 2022 },
  GY:  { name: "Guyana",          co2PerCapita:  4.2, year: 2022 },
  PA:  { name: "Panama",          co2PerCapita:  2.8, year: 2022 },
  DO:  { name: "Dom. Republic",   co2PerCapita:  2.4, year: 2022 },
  TN:  { name: "Tunisia",         co2PerCapita:  2.4, year: 2022 },
  CU:  { name: "Cuba",            co2PerCapita:  2.5, year: 2022 },
  JM:  { name: "Jamaica",         co2PerCapita:  2.5, year: 2022 },
  BT:  { name: "Bhutan",          co2PerCapita:  2.5, year: 2022 },
  MT:  { name: "Malta",           co2PerCapita:  3.3, year: 2022 },
  MU:  { name: "Mauritius",       co2PerCapita:  3.3, year: 2022 },
  SE:  { name: "Sweden",          co2PerCapita:  2.8, year: 2022 },
  UY:  { name: "Uruguay",         co2PerCapita:  2.2, year: 2022 },
  EG:  { name: "Egypt",           co2PerCapita:  2.5, year: 2022 },
  GE:  { name: "Georgia",         co2PerCapita:  2.2, year: 2022 },
  AM:  { name: "Armenia",         co2PerCapita:  1.9, year: 2022 },
  MD:  { name: "Moldova",         co2PerCapita:  1.8, year: 2022 },
  LK:  { name: "Sri Lanka",       co2PerCapita:  0.8, year: 2022 },
  ID:  { name: "Indonesia",       co2PerCapita:  2.6, year: 2022 },
  SY:  { name: "Syria",           co2PerCapita:  1.0, year: 2022 },

  // ── Lower emitters ────────────────────────────────────────────────────────
  BR:  { name: "Brazil",          co2PerCapita:  2.1, year: 2022 },
  IN:  { name: "India",           co2PerCapita:  1.9, year: 2022 },
  MA:  { name: "Morocco",         co2PerCapita:  1.7, year: 2022 },
  CO:  { name: "Colombia",        co2PerCapita:  1.7, year: 2022 },
  BZ:  { name: "Belize",          co2PerCapita:  1.7, year: 2022 },
  BO:  { name: "Bolivia",         co2PerCapita:  2.0, year: 2022 },
  PE:  { name: "Peru",            co2PerCapita:  2.0, year: 2022 },
  VE:  { name: "Venezuela",       co2PerCapita:  3.1, year: 2022 },
  CR:  { name: "Costa Rica",      co2PerCapita:  1.5, year: 2022 },
  KG:  { name: "Kyrgyzstan",      co2PerCapita:  1.5, year: 2022 },
  NA:  { name: "Namibia",         co2PerCapita:  1.8, year: 2022 },
  SZ:  { name: "Eswatini",        co2PerCapita:  0.9, year: 2022 },
  LS:  { name: "Lesotho",         co2PerCapita:  1.3, year: 2022 },
  TJ:  { name: "Tajikistan",      co2PerCapita:  1.0, year: 2022 },
  AF:  { name: "Afghanistan",     co2PerCapita:  0.2, year: 2022 },
  MM:  { name: "Myanmar",         co2PerCapita:  0.6, year: 2022 },
  KH:  { name: "Cambodia",        co2PerCapita:  0.7, year: 2022 },
  LA:  { name: "Laos",            co2PerCapita:  0.9, year: 2022 },
  TL:  { name: "Timor-Leste",     co2PerCapita:  0.4, year: 2022 },
  PH:  { name: "Philippines",     co2PerCapita:  1.3, year: 2022 },
  SN:  { name: "Senegal",         co2PerCapita:  0.7, year: 2022 },
  PY:  { name: "Paraguay",        co2PerCapita:  0.9, year: 2022 },
  EC:  { name: "Ecuador",         co2PerCapita:  2.2, year: 2022 },
  GT:  { name: "Guatemala",       co2PerCapita:  1.0, year: 2022 },
  HN:  { name: "Honduras",        co2PerCapita:  1.0, year: 2022 },
  SV:  { name: "El Salvador",     co2PerCapita:  1.0, year: 2022 },
  NI:  { name: "Nicaragua",       co2PerCapita:  0.9, year: 2022 },
  HT:  { name: "Haiti",           co2PerCapita:  0.3, year: 2022 },
  PK:  { name: "Pakistan",        co2PerCapita:  1.0, year: 2022 },
  NP:  { name: "Nepal",           co2PerCapita:  0.5, year: 2022 },
  MR:  { name: "Mauritania",      co2PerCapita:  0.9, year: 2022 },
  SD:  { name: "Sudan",           co2PerCapita:  0.5, year: 2022 },
  FJ:  { name: "Fiji",            co2PerCapita:  1.4, year: 2022 },
  PG:  { name: "Papua New Guinea",co2PerCapita:  0.8, year: 2022 },
  AO:  { name: "Angola",          co2PerCapita:  0.8, year: 2022 },
  CI:  { name: "Côte d'Ivoire",   co2PerCapita:  0.5, year: 2022 },
  CG:  { name: "Rep. of Congo",   co2PerCapita:  0.7, year: 2022 },
  GA:  { name: "Gabon",           co2PerCapita:  2.9, year: 2022 },
  CM:  { name: "Cameroon",        co2PerCapita:  0.3, year: 2022 },
  GH:  { name: "Ghana",           co2PerCapita:  0.6, year: 2022 },
  BJ:  { name: "Benin",           co2PerCapita:  0.5, year: 2022 },
  TG:  { name: "Togo",            co2PerCapita:  0.3, year: 2022 },
  NE:  { name: "Niger",           co2PerCapita:  0.1, year: 2022 },
  ML:  { name: "Mali",            co2PerCapita:  0.1, year: 2022 },
  BF:  { name: "Burkina Faso",    co2PerCapita:  0.1, year: 2022 },
  TD:  { name: "Chad",            co2PerCapita:  0.1, year: 2022 },
  GM:  { name: "Gambia",          co2PerCapita:  0.3, year: 2022 },
  GN:  { name: "Guinea",          co2PerCapita:  0.3, year: 2022 },
  SL:  { name: "Sierra Leone",    co2PerCapita:  0.1, year: 2022 },
  LR:  { name: "Liberia",         co2PerCapita:  0.2, year: 2022 },
  MG:  { name: "Madagascar",      co2PerCapita:  0.2, year: 2022 },
  KM:  { name: "Comoros",         co2PerCapita:  0.3, year: 2022 },
  CV:  { name: "Cape Verde",      co2PerCapita:  0.8, year: 2022 },
  ST:  { name: "São Tomé & Pr.",  co2PerCapita:  0.7, year: 2022 },
  DJ:  { name: "Djibouti",        co2PerCapita:  0.6, year: 2022 },
  ER:  { name: "Eritrea",         co2PerCapita:  0.1, year: 2022 },
  SO:  { name: "Somalia",         co2PerCapita:  0.1, year: 2022 },
  SS:  { name: "South Sudan",     co2PerCapita:  0.1, year: 2022 },

  // ── Very low emitters ─────────────────────────────────────────────────────
  BD:  { name: "Bangladesh",      co2PerCapita:  0.6, year: 2022 },
  NG:  { name: "Nigeria",         co2PerCapita:  0.6, year: 2022 },
  KE:  { name: "Kenya",           co2PerCapita:  0.4, year: 2022 },
  TZ:  { name: "Tanzania",        co2PerCapita:  0.2, year: 2022 },
  UG:  { name: "Uganda",          co2PerCapita:  0.1, year: 2022 },
  RW:  { name: "Rwanda",          co2PerCapita:  0.1, year: 2022 },
  BI:  { name: "Burundi",         co2PerCapita:  0.1, year: 2022 },
  ET:  { name: "Ethiopia",        co2PerCapita:  0.1, year: 2022 },
  ZM:  { name: "Zambia",          co2PerCapita:  0.3, year: 2022 },
  ZW:  { name: "Zimbabwe",        co2PerCapita:  0.7, year: 2022 },
  MZ:  { name: "Mozambique",      co2PerCapita:  0.1, year: 2022 },
  MW:  { name: "Malawi",          co2PerCapita:  0.1, year: 2022 },
  BW:  { name: "Botswana",        co2PerCapita:  2.7, year: 2022 },
  CD:  { name: "DR Congo",        co2PerCapita:  0.03, year: 2022 },
  CF:  { name: "Central Afr. Rep.",co2PerCapita: 0.1, year: 2022 },
  GQ:  { name: "Eq. Guinea",      co2PerCapita:  4.7, year: 2022 },
  YE:  { name: "Yemen",           co2PerCapita:  0.2, year: 2022 },
  KP:  { name: "North Korea",     co2PerCapita:  3.5, year: 2022 },
};

// ─── Cycling modal share ──────────────────────────────────────────────────────
// % of all daily trips made by bicycle.
// Sources: Eurobarometer 2022 (EU), ITDP Global Cycling Cities reports,
//          national transport surveys, academic literature (2020–2023).
// Note: national averages mask large urban/rural variation.
export const BASELINE_CYCLING: Record<string, { name: string; modalShare: number; year: number }> = {
  // ── Europe – very high ──────────────────────────────────────────────────
  NL: { name: "Netherlands",    modalShare: 27.0, year: 2022 },
  DK: { name: "Denmark",        modalShare: 18.0, year: 2022 },
  NO: { name: "Norway",         modalShare: 12.0, year: 2022 },
  DE: { name: "Germany",        modalShare: 11.0, year: 2022 },
  FI: { name: "Finland",        modalShare: 10.0, year: 2022 },
  SE: { name: "Sweden",         modalShare:  9.0, year: 2022 },
  BE: { name: "Belgium",        modalShare:  8.0, year: 2022 },
  CH: { name: "Switzerland",    modalShare:  8.0, year: 2022 },
  AT: { name: "Austria",        modalShare:  7.0, year: 2022 },
  CZ: { name: "Czech Republic", modalShare:  7.0, year: 2022 },
  LV: { name: "Latvia",         modalShare:  6.0, year: 2022 },
  HU: { name: "Hungary",        modalShare:  5.0, year: 2022 },
  LT: { name: "Lithuania",      modalShare:  5.0, year: 2022 },
  EE: { name: "Estonia",        modalShare:  5.0, year: 2022 },
  IS: { name: "Iceland",        modalShare:  5.0, year: 2022 },
  PL: { name: "Poland",         modalShare:  4.0, year: 2022 },
  SK: { name: "Slovakia",       modalShare:  4.0, year: 2022 },
  HR: { name: "Croatia",        modalShare:  4.0, year: 2022 },
  SI: { name: "Slovenia",       modalShare:  4.0, year: 2022 },
  BY: { name: "Belarus",        modalShare:  4.0, year: 2022 },
  BG: { name: "Bulgaria",       modalShare:  3.0, year: 2022 },
  RO: { name: "Romania",        modalShare:  3.0, year: 2022 },
  AL: { name: "Albania",        modalShare:  3.0, year: 2022 },
  UA: { name: "Ukraine",        modalShare:  3.0, year: 2022 },
  FR: { name: "France",         modalShare:  3.0, year: 2022 },
  IT: { name: "Italy",          modalShare:  3.0, year: 2022 },
  RS: { name: "Serbia",         modalShare:  3.0, year: 2022 },
  LU: { name: "Luxembourg",     modalShare:  2.0, year: 2022 },
  PT: { name: "Portugal",       modalShare:  2.0, year: 2022 },
  ES: { name: "Spain",          modalShare:  2.0, year: 2022 },
  GB: { name: "United Kingdom", modalShare:  2.0, year: 2022 },
  IE: { name: "Ireland",        modalShare:  2.0, year: 2022 },
  BA: { name: "Bosnia & Herz.", modalShare:  2.0, year: 2022 },
  ME: { name: "Montenegro",     modalShare:  2.0, year: 2022 },
  MK: { name: "N. Macedonia",   modalShare:  2.0, year: 2022 },
  MD: { name: "Moldova",        modalShare:  2.0, year: 2022 },
  MT: { name: "Malta",          modalShare:  2.0, year: 2022 },
  GR: { name: "Greece",         modalShare:  1.0, year: 2022 },
  CY: { name: "Cyprus",         modalShare:  1.0, year: 2022 },
  GE: { name: "Georgia",        modalShare:  1.0, year: 2022 },
  AM: { name: "Armenia",        modalShare:  1.0, year: 2022 },
  AZ: { name: "Azerbaijan",     modalShare:  1.0, year: 2022 },
  RU: { name: "Russia",         modalShare:  1.0, year: 2022 },

  // ── Asia – very high ────────────────────────────────────────────────────
  BD: { name: "Bangladesh",     modalShare: 20.0, year: 2022 }, // rickshaw/bike culture
  JP: { name: "Japan",          modalShare: 15.0, year: 2022 }, // strong urban cycling
  CU: { name: "Cuba",           modalShare: 15.0, year: 2021 }, // necessity cycling
  CN: { name: "China",          modalShare: 15.0, year: 2022 }, // declining but still high
  KH: { name: "Cambodia",       modalShare: 12.0, year: 2022 },
  IN: { name: "India",          modalShare: 10.0, year: 2022 }, // traditional + growing
  MM: { name: "Myanmar",        modalShare:  9.0, year: 2021 },
  NP: { name: "Nepal",          modalShare:  8.0, year: 2022 },
  PK: { name: "Pakistan",       modalShare:  8.0, year: 2022 },
  LA: { name: "Laos",           modalShare:  7.0, year: 2022 },
  VN: { name: "Vietnam",        modalShare:  6.0, year: 2022 },
  LK: { name: "Sri Lanka",      modalShare:  5.0, year: 2022 },
  TL: { name: "Timor-Leste",    modalShare:  5.0, year: 2021 },
  KP: { name: "North Korea",    modalShare:  5.0, year: 2020 },
  TW: { name: "Taiwan",         modalShare:  4.0, year: 2022 },
  TH: { name: "Thailand",       modalShare:  4.0, year: 2022 },
  PH: { name: "Philippines",    modalShare:  4.0, year: 2022 },
  MN: { name: "Mongolia",       modalShare:  3.0, year: 2021 },
  ID: { name: "Indonesia",      modalShare:  3.0, year: 2022 },
  AF: { name: "Afghanistan",    modalShare:  3.0, year: 2021 },
  TR: { name: "Turkey",         modalShare:  2.0, year: 2022 },
  KR: { name: "South Korea",    modalShare:  2.0, year: 2022 },
  SG: { name: "Singapore",      modalShare:  2.0, year: 2022 },
  IL: { name: "Israel",         modalShare:  2.0, year: 2022 },
  IR: { name: "Iran",           modalShare:  2.0, year: 2022 },
  IQ: { name: "Iraq",           modalShare:  2.0, year: 2021 },
  JO: { name: "Jordan",         modalShare:  1.0, year: 2022 },
  MY: { name: "Malaysia",       modalShare:  1.0, year: 2022 },
  BN: { name: "Brunei",         modalShare:  1.0, year: 2021 },
  KZ: { name: "Kazakhstan",     modalShare:  2.0, year: 2022 },
  UZ: { name: "Uzbekistan",     modalShare:  3.0, year: 2022 },
  KG: { name: "Kyrgyzstan",     modalShare:  3.0, year: 2021 },
  TJ: { name: "Tajikistan",     modalShare:  4.0, year: 2021 },
  SA: { name: "Saudi Arabia",   modalShare:  0.5, year: 2022 },
  AE: { name: "UAE",            modalShare:  0.5, year: 2022 },
  QA: { name: "Qatar",          modalShare:  0.5, year: 2022 },

  // ── Africa ──────────────────────────────────────────────────────────────
  UG: { name: "Uganda",         modalShare:  8.0, year: 2022 },
  KE: { name: "Kenya",          modalShare:  8.0, year: 2022 },
  RW: { name: "Rwanda",         modalShare:  8.0, year: 2022 },
  MG: { name: "Madagascar",     modalShare:  8.0, year: 2021 },
  BF: { name: "Burkina Faso",   modalShare:  7.0, year: 2021 },
  TZ: { name: "Tanzania",       modalShare:  7.0, year: 2022 },
  ET: { name: "Ethiopia",       modalShare:  6.0, year: 2022 },
  MZ: { name: "Mozambique",     modalShare:  6.0, year: 2021 },
  MW: { name: "Malawi",         modalShare:  6.0, year: 2021 },
  SD: { name: "Sudan",          modalShare:  5.0, year: 2021 },
  ML: { name: "Mali",           modalShare:  5.0, year: 2021 },
  SN: { name: "Senegal",        modalShare:  5.0, year: 2022 },
  CM: { name: "Cameroon",       modalShare:  5.0, year: 2021 },
  GH: { name: "Ghana",          modalShare:  5.0, year: 2022 },
  ZW: { name: "Zimbabwe",       modalShare:  5.0, year: 2021 },
  ZM: { name: "Zambia",         modalShare:  5.0, year: 2021 },
  HT: { name: "Haiti",          modalShare:  5.0, year: 2021 },
  NG: { name: "Nigeria",        modalShare:  4.0, year: 2022 },
  MA: { name: "Morocco",        modalShare:  4.0, year: 2022 },
  TD: { name: "Chad",           modalShare:  4.0, year: 2021 },
  AO: { name: "Angola",         modalShare:  4.0, year: 2021 },
  EG: { name: "Egypt",          modalShare:  3.0, year: 2022 },
  BI: { name: "Burundi",        modalShare:  7.0, year: 2021 },
  DZ: { name: "Algeria",        modalShare:  2.0, year: 2022 },
  TN: { name: "Tunisia",        modalShare:  3.0, year: 2022 },
  ZA: { name: "South Africa",   modalShare:  1.0, year: 2022 },
  NA: { name: "Namibia",        modalShare:  3.0, year: 2021 },
  BW: { name: "Botswana",       modalShare:  2.0, year: 2021 },

  // ── Americas ────────────────────────────────────────────────────────────
  CO: { name: "Colombia",       modalShare:  4.0, year: 2022 }, // Bogotá famous for cycling
  EC: { name: "Ecuador",        modalShare:  4.0, year: 2022 },
  BO: { name: "Bolivia",        modalShare:  4.0, year: 2022 },
  GT: { name: "Guatemala",      modalShare:  3.0, year: 2021 },
  HN: { name: "Honduras",       modalShare:  3.0, year: 2021 },
  NI: { name: "Nicaragua",      modalShare:  3.0, year: 2021 },
  CR: { name: "Costa Rica",     modalShare:  3.0, year: 2022 },
  BR: { name: "Brazil",         modalShare:  3.0, year: 2022 },
  PE: { name: "Peru",           modalShare:  3.0, year: 2022 },
  PY: { name: "Paraguay",       modalShare:  3.0, year: 2021 },
  UY: { name: "Uruguay",        modalShare:  3.0, year: 2022 },
  JM: { name: "Jamaica",        modalShare:  3.0, year: 2021 },
  MX: { name: "Mexico",         modalShare:  2.0, year: 2022 },
  AR: { name: "Argentina",      modalShare:  2.0, year: 2022 },
  CL: { name: "Chile",          modalShare:  2.0, year: 2022 },
  VE: { name: "Venezuela",      modalShare:  2.0, year: 2021 },
  SV: { name: "El Salvador",    modalShare:  2.0, year: 2021 },
  PA: { name: "Panama",         modalShare:  2.0, year: 2021 },
  DO: { name: "Dom. Republic",  modalShare:  2.0, year: 2021 },
  CA: { name: "Canada",         modalShare:  1.5, year: 2022 },
  AU: { name: "Australia",      modalShare:  1.5, year: 2022 },
  US: { name: "United States",  modalShare:  1.0, year: 2022 },
  NZ: { name: "New Zealand",    modalShare:  1.0, year: 2022 },
  TT: { name: "Trinidad & Tob.",modalShare:  1.0, year: 2021 },
  FJ: { name: "Fiji",           modalShare:  4.0, year: 2021 },
  PG: { name: "Papua New Guinea",modalShare: 5.0, year: 2021 },
};
