// Baseline annual data from Our World in Data / Global Carbon Project (2022-2023)
// Renewable % = share of electricity from renewables
// co2PerCapita = tonnes CO2 per person per year

export const COUNTRY_FLAGS: Record<string, string> = {
  NO: "🇳🇴", IS: "🇮🇸", AL: "🇦🇱", NP: "🇳🇵", BR: "🇧🇷",
  CA: "🇨🇦", SE: "🇸🇪", NZ: "🇳🇿", AT: "🇦🇹", CH: "🇨🇭",
  PT: "🇵🇹", DE: "🇩🇪", ES: "🇪🇸", FR: "🇫🇷", GB: "🇬🇧",
  IT: "🇮🇹", DK: "🇩🇰", FI: "🇫🇮", LV: "🇱🇻", LT: "🇱🇹",
  EE: "🇪🇪", HR: "🇭🇷", SK: "🇸🇰", SI: "🇸🇮", RO: "🇷🇴",
  HU: "🇭🇺", BG: "🇧🇬", PL: "🇵🇱", CZ: "🇨🇿", BE: "🇧🇪",
  NL: "🇳🇱", GR: "🇬🇷", US: "🇺🇸", AU: "🇦🇺", CN: "🇨🇳",
  IN: "🇮🇳", JP: "🇯🇵", KR: "🇰🇷", ZA: "🇿🇦", MX: "🇲🇽",
  AR: "🇦🇷", CL: "🇨🇱", CO: "🇨🇴", VE: "🇻🇪", PE: "🇵🇪",
  NG: "🇳🇬", ET: "🇪🇹", KE: "🇰🇪", MA: "🇲🇦", EG: "🇪🇬",
  SA: "🇸🇦", IR: "🇮🇷", IQ: "🇮🇶", TR: "🇹🇷", PK: "🇵🇰",
  BD: "🇧🇩", ID: "🇮🇩", PH: "🇵🇭", TH: "🇹🇭", VN: "🇻🇳",
  MY: "🇲🇾", SG: "🇸🇬", TW: "🇹🇼", UA: "🇺🇦", RU: "🇷🇺",
  KZ: "🇰🇿", AE: "🇦🇪", QA: "🇶🇦", KW: "🇰🇼", BH: "🇧🇭",
  LU: "🇱🇺", CY: "🇨🇾", MT: "🇲🇹", IE: "🇮🇪", IL: "🇮🇱",
  CR: "🇨🇷", UY: "🇺🇾", EC: "🇪🇨", PY: "🇵🇾", BO: "🇧🇴",
  GH: "🇬🇭", TZ: "🇹🇿", UG: "🇺🇬", ZW: "🇿🇼", ZM: "🇿🇲",
};

export const BASELINE_RENEWABLE: Record<string, { name: string; percent: number; breakdown: Record<string, number> }> = {
  NO: { name: "Norway",         percent: 98.5, breakdown: { hydro: 91, wind: 6, solar: 0.1, fossil: 2 } },
  IS: { name: "Iceland",        percent: 99.9, breakdown: { hydro: 70, wind: 0, solar: 0, other: 29.9 } }, // geothermal
  AL: { name: "Albania",        percent: 97.0, breakdown: { hydro: 97, wind: 0, solar: 0, fossil: 3 } },
  BR: { name: "Brazil",         percent: 88.0, breakdown: { hydro: 61, wind: 12, solar: 5, fossil: 12 } },
  CA: { name: "Canada",         percent: 83.0, breakdown: { hydro: 60, wind: 6, nuclear: 15, fossil: 17 } },
  SE: { name: "Sweden",         percent: 98.6, breakdown: { hydro: 44, wind: 17, nuclear: 30, solar: 1, fossil: 1 } },
  NZ: { name: "New Zealand",    percent: 85.0, breakdown: { hydro: 57, wind: 9, solar: 2, fossil: 15 } },
  AT: { name: "Austria",        percent: 78.0, breakdown: { hydro: 62, wind: 10, solar: 5, fossil: 22 } },
  CH: { name: "Switzerland",    percent: 91.0, breakdown: { hydro: 57, wind: 0.2, solar: 6, nuclear: 27, fossil: 9 } },
  PT: { name: "Portugal",       percent: 61.0, breakdown: { hydro: 26, wind: 26, solar: 6, fossil: 39 } },
  DK: { name: "Denmark",        percent: 77.0, breakdown: { wind: 55, solar: 6, hydro: 0.1, fossil: 23 } },
  DE: { name: "Germany",        percent: 59.0, breakdown: { wind: 31, solar: 11, hydro: 3.5, fossil: 41 } },
  ES: { name: "Spain",          percent: 57.0, breakdown: { wind: 23, solar: 14, hydro: 7, nuclear: 20, fossil: 43 } },
  FR: { name: "France",         percent: 92.0, breakdown: { nuclear: 72, hydro: 11, wind: 7, solar: 2, fossil: 8 } },
  GB: { name: "United Kingdom", percent: 50.0, breakdown: { wind: 29, nuclear: 15, solar: 5, hydro: 2, fossil: 50 } },
  IT: { name: "Italy",          percent: 40.0, breakdown: { hydro: 18, solar: 11, wind: 7, fossil: 60 } },
  FI: { name: "Finland",        percent: 85.0, breakdown: { hydro: 24, nuclear: 34, wind: 14, fossil: 15 } },
  IE: { name: "Ireland",        percent: 42.0, breakdown: { wind: 34, hydro: 3, solar: 1, fossil: 58 } },
  NL: { name: "Netherlands",    percent: 36.0, breakdown: { wind: 22, solar: 11, fossil: 64 } },
  BE: { name: "Belgium",        percent: 31.0, breakdown: { nuclear: 46, wind: 13, solar: 7, fossil: 69 } },
  PL: { name: "Poland",         percent: 27.0, breakdown: { wind: 14, solar: 5, hydro: 1, fossil: 73 } },
  CZ: { name: "Czech Republic", percent: 43.0, breakdown: { nuclear: 38, hydro: 2, solar: 3, wind: 1, fossil: 57 } },
  US: { name: "United States",  percent: 21.0, breakdown: { wind: 10, solar: 5, hydro: 6, nuclear: 18, fossil: 61 } },
  AU: { name: "Australia",      percent: 35.0, breakdown: { solar: 15, wind: 13, hydro: 6, fossil: 65 } },
  CN: { name: "China",          percent: 29.0, breakdown: { hydro: 16, wind: 8, solar: 5, nuclear: 5, fossil: 71 } },
  IN: { name: "India",          percent: 22.0, breakdown: { hydro: 10, wind: 6, solar: 6, fossil: 78 } },
  JP: { name: "Japan",          percent: 23.0, breakdown: { hydro: 8, solar: 9, wind: 1, nuclear: 7, fossil: 77 } },
  KR: { name: "South Korea",    percent: 9.0,  breakdown: { nuclear: 28, hydro: 1, solar: 4, wind: 1, fossil: 65 } },
  ZA: { name: "South Africa",   percent: 10.0, breakdown: { hydro: 1, wind: 4, solar: 3, nuclear: 5, fossil: 90 } },
  MX: { name: "Mexico",         percent: 25.0, breakdown: { hydro: 10, wind: 8, solar: 5, fossil: 75 } },
  AR: { name: "Argentina",      percent: 38.0, breakdown: { hydro: 25, wind: 9, solar: 2, nuclear: 6, fossil: 62 } },
  CL: { name: "Chile",          percent: 56.0, breakdown: { hydro: 26, wind: 12, solar: 16, fossil: 44 } },
  CO: { name: "Colombia",       percent: 69.0, breakdown: { hydro: 66, wind: 1, solar: 1, fossil: 31 } },
  SA: { name: "Saudi Arabia",   percent: 3.0,  breakdown: { solar: 2, fossil: 97 } },
  AE: { name: "UAE",            percent: 8.0,  breakdown: { solar: 5, nuclear: 5, fossil: 92 } },
  QA: { name: "Qatar",          percent: 0.1,  breakdown: { fossil: 100 } },
  KW: { name: "Kuwait",         percent: 0.2,  breakdown: { solar: 0.2, fossil: 100 } },
  TR: { name: "Turkey",         percent: 45.0, breakdown: { hydro: 28, wind: 11, solar: 5, fossil: 55 } },
  IR: { name: "Iran",           percent: 8.0,  breakdown: { hydro: 6, nuclear: 2, fossil: 92 } },
  RU: { name: "Russia",         percent: 20.0, breakdown: { hydro: 17, nuclear: 20, wind: 0.3, fossil: 60 } },
  UA: { name: "Ukraine",        percent: 67.0, breakdown: { nuclear: 56, hydro: 7, wind: 3, solar: 5, fossil: 33 } },
  KE: { name: "Kenya",          percent: 75.0, breakdown: { hydro: 30, wind: 15, solar: 3, other: 27, fossil: 25 } },
  ET: { name: "Ethiopia",       percent: 97.0, breakdown: { hydro: 95, wind: 2, fossil: 3 } },
  NG: { name: "Nigeria",        percent: 22.0, breakdown: { hydro: 20, solar: 1, fossil: 78 } },
  MA: { name: "Morocco",        percent: 31.0, breakdown: { hydro: 5, wind: 16, solar: 7, fossil: 69 } },
  EG: { name: "Egypt",          percent: 12.0, breakdown: { hydro: 7, wind: 3, solar: 2, fossil: 88 } },
  PK: { name: "Pakistan",       percent: 34.0, breakdown: { hydro: 26, nuclear: 8, wind: 1, fossil: 66 } },
  BD: { name: "Bangladesh",     percent: 3.0,  breakdown: { solar: 2, fossil: 97 } },
  ID: { name: "Indonesia",      percent: 15.0, breakdown: { hydro: 7, solar: 2, wind: 0.1, fossil: 85 } },
  PH: { name: "Philippines",    percent: 22.0, breakdown: { hydro: 11, wind: 3, solar: 2, fossil: 78 } },
  TH: { name: "Thailand",       percent: 20.0, breakdown: { hydro: 5, solar: 8, wind: 3, fossil: 80 } },
  VN: { name: "Vietnam",        percent: 42.0, breakdown: { hydro: 29, solar: 10, wind: 3, fossil: 58 } },
  MY: { name: "Malaysia",       percent: 26.0, breakdown: { hydro: 22, solar: 4, fossil: 74 } },
  SG: { name: "Singapore",      percent: 4.0,  breakdown: { solar: 3, fossil: 97 } },
  CR: { name: "Costa Rica",     percent: 99.0, breakdown: { hydro: 75, wind: 13, solar: 1, other: 10, fossil: 1 } },
  UY: { name: "Uruguay",        percent: 98.0, breakdown: { wind: 41, hydro: 30, solar: 5, fossil: 2 } },
  PY: { name: "Paraguay",       percent: 100.0, breakdown: { hydro: 100, fossil: 0 } },
  EC: { name: "Ecuador",        percent: 78.0, breakdown: { hydro: 73, solar: 3, wind: 1, fossil: 22 } },
  IL: { name: "Israel",         percent: 12.0, breakdown: { solar: 10, fossil: 88 } },
  LU: { name: "Luxembourg",     percent: 33.0, breakdown: { hydro: 6, wind: 14, solar: 10, fossil: 67 } },
};

export const BASELINE_CARBON: Record<string, { name: string; co2PerCapita: number; year: number }> = {
  QA:  { name: "Qatar",          co2PerCapita: 31.7, year: 2022 },
  KW:  { name: "Kuwait",         co2PerCapita: 23.0, year: 2022 },
  BH:  { name: "Bahrain",        co2PerCapita: 21.7, year: 2022 },
  AE:  { name: "UAE",            co2PerCapita: 20.1, year: 2022 },
  AU:  { name: "Australia",      co2PerCapita: 14.8, year: 2022 },
  SA:  { name: "Saudi Arabia",   co2PerCapita: 14.0, year: 2022 },
  US:  { name: "United States",  co2PerCapita: 13.7, year: 2022 },
  KZ:  { name: "Kazakhstan",     co2PerCapita: 13.2, year: 2022 },
  LU:  { name: "Luxembourg",     co2PerCapita: 12.0, year: 2022 },
  CA:  { name: "Canada",         co2PerCapita: 11.6, year: 2022 },
  RU:  { name: "Russia",         co2PerCapita: 11.0, year: 2022 },
  KR:  { name: "South Korea",    co2PerCapita: 11.0, year: 2022 },
  JP:  { name: "Japan",          co2PerCapita: 8.5,  year: 2022 },
  DE:  { name: "Germany",        co2PerCapita: 7.9,  year: 2022 },
  IR:  { name: "Iran",           co2PerCapita: 7.8,  year: 2022 },
  NL:  { name: "Netherlands",    co2PerCapita: 7.4,  year: 2022 },
  PL:  { name: "Poland",         co2PerCapita: 7.3,  year: 2022 },
  TR:  { name: "Turkey",         co2PerCapita: 6.4,  year: 2022 },
  MY:  { name: "Malaysia",       co2PerCapita: 6.4,  year: 2022 },
  ZA:  { name: "South Africa",   co2PerCapita: 6.2,  year: 2022 },
  CZ:  { name: "Czech Republic", co2PerCapita: 6.2,  year: 2022 },
  CN:  { name: "China",          co2PerCapita: 6.1,  year: 2022 },
  BE:  { name: "Belgium",        co2PerCapita: 6.1,  year: 2022 },
  AT:  { name: "Austria",        co2PerCapita: 5.8,  year: 2022 },
  IE:  { name: "Ireland",        co2PerCapita: 5.6,  year: 2022 },
  GB:  { name: "United Kingdom", co2PerCapita: 4.8,  year: 2022 },
  SG:  { name: "Singapore",      co2PerCapita: 4.6,  year: 2022 },
  IQ:  { name: "Iraq",           co2PerCapita: 4.5,  year: 2022 },
  ES:  { name: "Spain",          co2PerCapita: 4.4,  year: 2022 },
  IT:  { name: "Italy",          co2PerCapita: 4.4,  year: 2022 },
  FR:  { name: "France",         co2PerCapita: 3.9,  year: 2022 },
  MX:  { name: "Mexico",         co2PerCapita: 3.7,  year: 2022 },
  TH:  { name: "Thailand",       co2PerCapita: 3.5,  year: 2022 },
  ID:  { name: "Indonesia",      co2PerCapita: 2.6,  year: 2022 },
  AR:  { name: "Argentina",      co2PerCapita: 4.0,  year: 2022 },
  UA:  { name: "Ukraine",        co2PerCapita: 3.5,  year: 2022 },
  EG:  { name: "Egypt",          co2PerCapita: 2.5,  year: 2022 },
  VN:  { name: "Vietnam",        co2PerCapita: 3.5,  year: 2022 },
  PK:  { name: "Pakistan",       co2PerCapita: 1.0,  year: 2022 },
  IN:  { name: "India",          co2PerCapita: 1.9,  year: 2022 },
  PH:  { name: "Philippines",    co2PerCapita: 1.3,  year: 2022 },
  BD:  { name: "Bangladesh",     co2PerCapita: 0.6,  year: 2022 },
  NG:  { name: "Nigeria",        co2PerCapita: 0.6,  year: 2022 },
  CH:  { name: "Switzerland",    co2PerCapita: 3.8,  year: 2022 },
  SE:  { name: "Sweden",         co2PerCapita: 2.8,  year: 2022 },
  NO:  { name: "Norway",         co2PerCapita: 7.2,  year: 2022 },
  DK:  { name: "Denmark",        co2PerCapita: 4.5,  year: 2022 },
  FI:  { name: "Finland",        co2PerCapita: 5.9,  year: 2022 },
  NZ:  { name: "New Zealand",    co2PerCapita: 6.1,  year: 2022 },
  BR:  { name: "Brazil",         co2PerCapita: 2.1,  year: 2022 },
  CL:  { name: "Chile",          co2PerCapita: 4.1,  year: 2022 },
  CO:  { name: "Colombia",       co2PerCapita: 1.7,  year: 2022 },
  CR:  { name: "Costa Rica",     co2PerCapita: 1.5,  year: 2022 },
  UY:  { name: "Uruguay",        co2PerCapita: 2.2,  year: 2022 },
  PY:  { name: "Paraguay",       co2PerCapita: 0.9,  year: 2022 },
  PT:  { name: "Portugal",       co2PerCapita: 3.9,  year: 2022 },
  MA:  { name: "Morocco",        co2PerCapita: 1.7,  year: 2022 },
  KE:  { name: "Kenya",          co2PerCapita: 0.4,  year: 2022 },
  ET:  { name: "Ethiopia",       co2PerCapita: 0.1,  year: 2022 },
  TZ:  { name: "Tanzania",       co2PerCapita: 0.2,  year: 2022 },
  GH:  { name: "Ghana",          co2PerCapita: 0.6,  year: 2022 },
  IL:  { name: "Israel",         co2PerCapita: 6.4,  year: 2022 },
  IS:  { name: "Iceland",        co2PerCapita: 9.1,  year: 2022 },
};
